## application-pages.roperties
## if there is a hash (#) leave line
## name : type : visibility : color : width
## capture page should have display(D) and hidden(H) which means input field will be text or hidden
pages.FIRSTP=CAP-FFN001:I:D:B:10%,FFN002:I:D:W:10%,FFN003:I:D:B:10%,FFN004:I:D:W:10%,FFN005:I:H:R:10%
## confirm page should have display(D) and hidden(H) which means input type as text but read only and also have hidden fields as read only
pages.FIRST1=CON-FFN001:I:D:B:10%,FFN002:I:D:W:10%,FFN003:I:D:B:10%,FFN004:I:D:W:10%,FFN005:I:H:R:10%,FFN006:I:D:R:10%
## acknowledgement page should not have input fields as text must only show values
pages.FIRST2=ACK-FFN001:I:D:B:10%,FFN002:I:D:W:10%,FFN003:I:D:B:10%,FFN004:I:D:W:10%,FFN005:I:D:R:10%

