spring.application.name=employee-management
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
spring.datasource.username=system
spring.datasource.password=Swaroop123

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
<<<<<<< HEAD
spring.jpa.show-sql=true

## adding below to access other files and build dynamic pages in react js
spring.config.import=classpath:application-pages.properties
=======
spring.jpa.show-sql=true
>>>>>>> 862f1b99b1ef1ced8e7ab519332f328e0bcad9f1
